#!/usr/bin/env node

import { readdir, readFile, stat, writeFile } from "node:fs/promises";
import path from "node:path";

const root = process.cwd();
const notesRoot = path.join(root, "notes");
const demosRoot = path.join(root, "demos");
const outputPath = path.join(root, "meta", "index.md");
const generatedNotice =
  "<!-- Generated from notes/**/*.md front matter by scripts/build-index.mjs. Do not edit this file directly. -->";

function usage() {
  console.log(`Usage:
  node scripts/build-index.mjs
  node scripts/build-index.mjs --check

Options:
  --check   Validate that meta/index.md is up to date without writing.
`);
}

function parseArgs(argv) {
  const args = new Set(argv);
  if (args.has("--help") || args.has("-h")) {
    usage();
    process.exit(0);
  }
  for (const arg of args) {
    if (arg !== "--check") {
      throw new Error(`Unknown option: ${arg}`);
    }
  }
  return { check: args.has("--check") };
}

async function pathExists(filePath) {
  try {
    await stat(filePath);
    return true;
  } catch (error) {
    if (error.code === "ENOENT") return false;
    throw error;
  }
}

async function listDirectories(dir) {
  if (!(await pathExists(dir))) return [];
  const entries = await readdir(dir, { withFileTypes: true });
  return entries
    .filter((entry) => entry.isDirectory() && !entry.name.startsWith("."))
    .map((entry) => entry.name)
    .sort();
}

async function listMarkdownFiles(dir) {
  if (!(await pathExists(dir))) return [];
  const entries = await readdir(dir, { withFileTypes: true });
  return entries
    .filter((entry) => entry.isFile() && entry.name.endsWith(".md"))
    .map((entry) => entry.name)
    .sort();
}

function splitFrontmatter(markdown) {
  const match = markdown.match(/^---\r?\n([\s\S]*?)\r?\n---\r?\n?/);
  if (!match) return { frontmatter: "", body: markdown };
  return { frontmatter: match[1], body: markdown.slice(match[0].length) };
}

function stripQuotes(value) {
  const trimmed = value.trim();
  const quoted = trimmed.match(/^"(.*)"$/) || trimmed.match(/^'(.*)'$/);
  return quoted ? quoted[1] : trimmed;
}

function parseTopics(frontmatter) {
  const match = frontmatter.match(/^topics:\s*\[(.*)\]\s*$/m);
  if (!match) return [];
  return match[1]
    .split(",")
    .map((item) => stripQuotes(item))
    .filter(Boolean);
}

function parseSummary(frontmatter) {
  const match = frontmatter.match(/^summary:\s*(.+)$/m);
  if (!match) return "";
  return stripQuotes(match[1]);
}

function parseTitle(body) {
  const match = body.match(/^#\s+(.+)$/m);
  return match ? match[1].trim() : "";
}

async function findDemoFile(chapter, baseName) {
  const chapterDemoDir = path.join(demosRoot, chapter);
  if (!(await pathExists(chapterDemoDir))) return null;
  const entries = await readdir(chapterDemoDir, { withFileTypes: true });
  const match = entries.find(
    (entry) => entry.isFile() && path.parse(entry.name).name === baseName,
  );
  return match ? match.name : null;
}

function toPosixPath(value) {
  return value.split(path.sep).join("/");
}

function renderMarkdownLink(label, href) {
  return `[${label}](<${href.replaceAll(">", "%3E")}>)`;
}

async function collectEntries() {
  const chapters = await listDirectories(notesRoot);
  const entries = [];

  for (const chapter of chapters) {
    const chapterDir = path.join(notesRoot, chapter);
    const files = await listMarkdownFiles(chapterDir);

    for (const file of files) {
      const filePath = path.join(chapterDir, file);
      const markdown = await readFile(filePath, "utf8");
      const { frontmatter, body } = splitFrontmatter(markdown);
      const baseName = path.parse(file).name;
      const demoFile = await findDemoFile(chapter, baseName);

      entries.push({
        chapter,
        file,
        title: parseTitle(body) || baseName,
        topics: parseTopics(frontmatter),
        summary: parseSummary(frontmatter),
        notesRelPath: toPosixPath(path.join("..", "notes", chapter, file)),
        demoRelPath: demoFile
          ? toPosixPath(path.join("..", "demos", chapter, demoFile))
          : null,
      });
    }
  }

  return entries;
}

function renderByChapter(entries) {
  const lines = ["## 依章節瀏覽", ""];
  const chapters = [...new Set(entries.map((entry) => entry.chapter))];

  for (const chapter of chapters) {
    lines.push(`### ${chapter}`, "");
    for (const entry of entries.filter((item) => item.chapter === chapter)) {
      lines.push(`- ${renderMarkdownLink(entry.title, entry.notesRelPath)}`);
      if (entry.topics.length) lines.push(`  - topics: ${entry.topics.join(", ")}`);
      if (entry.summary) lines.push(`  - summary: ${entry.summary}`);
      if (entry.demoRelPath) {
        lines.push(`  - demo: ${renderMarkdownLink(`${entry.title} demo`, entry.demoRelPath)}`);
      }
    }
    lines.push("");
  }

  return lines;
}

function renderByTopic(entries) {
  const lines = ["## 依主題瀏覽", ""];
  const topicMap = new Map();

  for (const entry of entries) {
    for (const topic of entry.topics) {
      if (!topicMap.has(topic)) topicMap.set(topic, []);
      topicMap.get(topic).push(entry);
    }
  }

  const topics = [...topicMap.keys()].sort((a, b) => a.localeCompare(b, "zh-Hant"));
  if (!topics.length) {
    lines.push("（目前尚無任何 notes 標記 topics）", "");
    return lines;
  }

  for (const topic of topics) {
    lines.push(`### ${topic}`, "");
    for (const entry of topicMap.get(topic)) {
      lines.push(`- ${renderMarkdownLink(entry.title, entry.notesRelPath)}（${entry.chapter}）`);
    }
    lines.push("");
  }

  return lines;
}

function renderUntagged(entries) {
  const lines = ["## 尚未標記 metadata", ""];
  const untagged = entries.filter((entry) => !entry.topics.length || !entry.summary);

  if (!untagged.length) {
    lines.push("（所有 notes 都已標記 topics 與 summary）", "");
    return lines;
  }

  lines.push(
    "以下 notes 缺少 `topics` 或 `summary`，可使用 `notes-index-metadata` skill 補上：",
    "",
  );
  for (const entry of untagged) {
    lines.push(`- notes/${entry.chapter}/${entry.file}`);
  }
  lines.push("");

  return lines;
}

function renderIndex(entries) {
  const lines = [
    generatedNotice,
    "",
    "# Notes 索引",
    "",
    "> 本檔案由 `scripts/build-index.mjs` 自動產生，請勿手動編輯。",
    "> 如需更新，請修改對應 notes 的 front matter（`topics`/`summary`）後重新執行：",
    ">",
    "> ```text",
    "> node scripts/build-index.mjs",
    "> ```",
    "",
    ...renderByChapter(entries),
    ...renderByTopic(entries),
    ...renderUntagged(entries),
  ];

  return `${lines.join("\n").replace(/\n+$/, "")}\n`;
}

async function main() {
  const options = parseArgs(process.argv.slice(2));
  const entries = await collectEntries();
  const markdown = renderIndex(entries);

  if (options.check) {
    const current = (await pathExists(outputPath)) ? await readFile(outputPath, "utf8") : null;
    if (current !== markdown) {
      throw new Error(`${path.relative(root, outputPath)} is not up to date`);
    }
    console.log(`Checked ${path.relative(root, outputPath)}`);
    return;
  }

  await writeFile(outputPath, markdown);
  console.log(`Built ${path.relative(root, outputPath)} (${entries.length} notes)`);
}

main().catch((error) => {
  console.error(error.message);
  process.exit(1);
});
