#!/usr/bin/env node

import { cp, mkdir, readdir, readFile, rm, stat, writeFile } from "node:fs/promises";
import path from "node:path";

const root = process.cwd();
const sourceRoot = path.join(root, "skills-src");
const claudeRoot = path.join(root, ".claude", "skills");
const codexRoot = path.join(root, ".codex", "skills");
const generatedNotice = "<!-- Generated from skills-src. Do not edit this file directly. -->";
const resourceDirs = new Set(["references", "scripts", "assets"]);

function usage() {
  console.log(`Usage:
  node scripts/build-skills.mjs --import-claude
  node scripts/build-skills.mjs

Options:
  --import-claude   Create missing skills-src entries from .claude/skills before building.
  --check           Validate that generated files are up to date without writing.
`);
}

function parseArgs(argv) {
  const args = new Set(argv);
  if (args.has("--help") || args.has("-h")) {
    usage();
    process.exit(0);
  }
  for (const arg of args) {
    if (!["--import-claude", "--check"].includes(arg)) {
      throw new Error(`Unknown option: ${arg}`);
    }
  }
  return {
    importClaude: args.has("--import-claude"),
    check: args.has("--check"),
  };
}

function parseFrontmatter(markdown, filePath) {
  const match = markdown.match(/^---\n([\s\S]*?)\n---\n?/);
  if (!match) {
    throw new Error(`${filePath} is missing YAML frontmatter`);
  }
  return {
    yaml: parseYaml(match[1], filePath),
    body: markdown.slice(match[0].length),
  };
}

function validateSkillMetadata(yaml, folderName, filePath, platform) {
  if (yaml.name !== folderName) {
    throw new Error(`${filePath} name "${yaml.name}" does not match folder "${folderName}"`);
  }
  assertSkillName(yaml.name, filePath);
  if (!yaml.description || typeof yaml.description !== "string") {
    throw new Error(`${filePath} is missing a string description`);
  }
  if (platform === "codex") {
    const keys = Object.keys(yaml);
    const unsupported = keys.filter((key) => !["name", "description"].includes(key));
    if (unsupported.length) {
      throw new Error(`${filePath} has Codex-unsupported frontmatter keys: ${unsupported.join(", ")}`);
    }
  }
}

function parseYaml(text, filePath) {
  const data = {};
  let currentBlockKey = null;
  let currentBlockIndent = 0;
  let currentMapKey = null;

  for (const rawLine of text.split(/\r?\n/)) {
    if (!rawLine.trim()) {
      if (currentBlockKey) data[currentBlockKey] += "\n";
      continue;
    }

    const indent = rawLine.match(/^ */)[0].length;
    const line = rawLine.trimEnd();

    if (currentBlockKey) {
      if (indent >= currentBlockIndent) {
        data[currentBlockKey] += `${line.slice(currentBlockIndent)}\n`;
        continue;
      }
      data[currentBlockKey] = data[currentBlockKey].replace(/\n+$/, "");
      currentBlockKey = null;
    }

    if (indent === 0) {
      currentMapKey = null;
      const blockMatch = line.match(/^([A-Za-z0-9_-]+):\s*\|\s*$/);
      if (blockMatch) {
        currentBlockKey = blockMatch[1];
        currentBlockIndent = 2;
        data[currentBlockKey] = "";
        continue;
      }

      const scalarMatch = line.match(/^([A-Za-z0-9_-]+):(?:\s*(.*))?$/);
      if (!scalarMatch) {
        throw new Error(`Unsupported YAML line in ${filePath}: ${rawLine}`);
      }
      const [, key, value = ""] = scalarMatch;
      if (value === "") {
        data[key] = {};
        currentMapKey = key;
      } else {
        data[key] = parseScalar(value);
      }
      continue;
    }

    if (indent === 2 && currentMapKey) {
      const nestedMatch = line.trim().match(/^([A-Za-z0-9_-]+):(?:\s*(.*))?$/);
      if (!nestedMatch) {
        throw new Error(`Unsupported nested YAML line in ${filePath}: ${rawLine}`);
      }
      const [, key, value = ""] = nestedMatch;
      data[currentMapKey][key] = parseScalar(value);
      continue;
    }

    throw new Error(`Unsupported YAML indentation in ${filePath}: ${rawLine}`);
  }

  if (currentBlockKey) {
    data[currentBlockKey] = data[currentBlockKey].replace(/\n+$/, "");
  }

  return data;
}

function parseScalar(value) {
  if (value === "true") return true;
  if (value === "false") return false;
  if (value === "null") return null;
  const quoted = value.match(/^"(.*)"$/) || value.match(/^'(.*)'$/);
  return quoted ? quoted[1] : value;
}

function yamlScalar(value) {
  if (typeof value === "boolean") return value ? "true" : "false";
  if (value === null) return "null";
  const stringValue = String(value);
  if (/^[A-Za-z0-9_-]+$/.test(stringValue)) return stringValue;
  if (stringValue.includes("\n") || stringValue.length > 100 || /[:#{}[\],&*?|<>=!%@`]/.test(stringValue)) {
    return `|\n${stringValue.split(/\r?\n/).map((line) => `  ${line}`).join("\n")}`;
  }
  return stringValue;
}

function stringifyYaml(data, keys) {
  const lines = [];
  for (const key of keys) {
    if (!(key in data) || data[key] === undefined) continue;
    const value = data[key];
    if (value && typeof value === "object" && !Array.isArray(value)) {
      const entries = Object.entries(value).filter(([, entryValue]) => entryValue !== undefined);
      if (!entries.length) continue;
      lines.push(`${key}:`);
      for (const [nestedKey, nestedValue] of entries) {
        lines.push(`  ${nestedKey}: ${yamlScalar(nestedValue)}`);
      }
      continue;
    }
    lines.push(`${key}: ${yamlScalar(value)}`);
  }
  return `${lines.join("\n")}\n`;
}

function assertSkillName(name, context) {
  if (!/^[a-z0-9][a-z0-9-]{0,62}$/.test(name)) {
    throw new Error(`${context} has invalid skill name "${name}". Use lowercase letters, digits, and hyphens only.`);
  }
}

async function pathExists(filePath) {
  try {
    await stat(filePath);
    return true;
  } catch (error) {
    if (error.code === "ENOENT") return false;
    throw error;
  }
}

async function listDirectories(dir) {
  if (!(await pathExists(dir))) return [];
  const entries = await readdir(dir, { withFileTypes: true });
  return entries.filter((entry) => entry.isDirectory() && !entry.name.startsWith(".")).map((entry) => entry.name).sort();
}

async function importClaudeSkills() {
  const skillNames = await listDirectories(claudeRoot);
  await mkdir(sourceRoot, { recursive: true });

  for (const skillName of skillNames) {
    assertSkillName(skillName, path.join(".claude", "skills", skillName));
    const sourceDir = path.join(sourceRoot, skillName);
    if (await pathExists(sourceDir)) continue;

    const claudeSkillDir = path.join(claudeRoot, skillName);
    const skillFile = path.join(claudeSkillDir, "SKILL.md");
    const markdown = await readFile(skillFile, "utf8");
    const { yaml, body } = parseFrontmatter(markdown, skillFile);
    if (yaml.name !== skillName) {
      throw new Error(`${skillFile} name "${yaml.name}" does not match folder "${skillName}"`);
    }
    if (!yaml.description) {
      throw new Error(`${skillFile} is missing description`);
    }

    await mkdir(sourceDir, { recursive: true });
    await writeFile(
      path.join(sourceDir, "skill.yaml"),
      stringifyYaml(
        {
          name: yaml.name,
          description: yaml.description,
          claude: Object.fromEntries(Object.entries(yaml).filter(([key]) => !["name", "description"].includes(key))),
        },
        ["name", "description", "claude"],
      ),
    );
    await writeFile(path.join(sourceDir, "instructions.md"), body);

    const entries = await readdir(claudeSkillDir, { withFileTypes: true });
    for (const entry of entries) {
      if (entry.name === "SKILL.md" || entry.name === ".DS_Store") continue;
      const from = path.join(claudeSkillDir, entry.name);
      const to = path.join(sourceDir, entry.name);
      await cp(from, to, { recursive: true });
    }

    console.log(`Imported ${skillName}`);
  }
}

async function readSkillSource(skillName) {
  const skillDir = path.join(sourceRoot, skillName);
  const yamlPath = path.join(skillDir, "skill.yaml");
  const instructionsPath = path.join(skillDir, "instructions.md");
  const yaml = parseYaml(await readFile(yamlPath, "utf8"), yamlPath);

  assertSkillName(skillName, skillDir);
  if (yaml.name !== skillName) {
    throw new Error(`${yamlPath} name "${yaml.name}" does not match folder "${skillName}"`);
  }
  if (!yaml.description) {
    throw new Error(`${yamlPath} is missing description`);
  }

  const instructions = await readFile(instructionsPath, "utf8");
  const overlaysDir = path.join(skillDir, "overlays");
  const claudeOverlayPath = path.join(overlaysDir, "claude.md");
  const codexOverlayPath = path.join(overlaysDir, "codex.md");

  return {
    skillDir,
    yaml,
    instructions,
    claudeOverlay: (await pathExists(claudeOverlayPath)) ? await readFile(claudeOverlayPath, "utf8") : "",
    codexOverlay: (await pathExists(codexOverlayPath)) ? await readFile(codexOverlayPath, "utf8") : "",
  };
}

// Skill installers reject descriptions containing angle-bracket "XML tags".
// Authors may write natural placeholders like `<章節>` in skill.yaml; convert
// the half-width brackets to full-width so the generated frontmatter is safe.
function sanitizeDescription(description) {
  return description.replace(/</g, "〈").replace(/>/g, "〉");
}

function renderSkillMarkdown(source, platform) {
  const platformYaml = source.yaml[platform] && typeof source.yaml[platform] === "object" ? source.yaml[platform] : {};
  const description = sanitizeDescription(source.yaml.description);
  const frontmatter =
    platform === "claude"
      ? { name: source.yaml.name, description, ...platformYaml }
      : { name: source.yaml.name, description };
  const overlay = platform === "claude" ? source.claudeOverlay : source.codexOverlay;
  const bodyParts = [generatedNotice, source.instructions.trimEnd()];
  if (overlay.trim()) {
    bodyParts.push(overlay.trimEnd());
  }
  return `---\n${stringifyYaml(frontmatter, Object.keys(frontmatter).filter((key) => frontmatter[key] !== undefined))}---\n\n${bodyParts.join("\n\n")}\n`;
}

async function copyResources(sourceDir, targetDir) {
  const entries = await readdir(sourceDir, { withFileTypes: true });
  for (const entry of entries) {
    if (!resourceDirs.has(entry.name)) continue;
    await cp(path.join(sourceDir, entry.name), path.join(targetDir, entry.name), { recursive: true });
  }

  const extraEntries = await readdir(sourceDir, { withFileTypes: true });
  for (const entry of extraEntries) {
    if (["skill.yaml", "instructions.md", "overlays", ".DS_Store"].includes(entry.name) || resourceDirs.has(entry.name)) continue;
    await cp(path.join(sourceDir, entry.name), path.join(targetDir, entry.name), { recursive: true });
  }
}

async function writeGeneratedSkill(source, platform, check) {
  const targetRoot = platform === "claude" ? claudeRoot : codexRoot;
  const targetDir = path.join(targetRoot, source.yaml.name);
  const markdown = renderSkillMarkdown(source, platform);
  const skillPath = path.join(targetDir, "SKILL.md");

  if (check) {
    const current = (await pathExists(skillPath)) ? await readFile(skillPath, "utf8") : null;
    if (current !== markdown) {
      throw new Error(`${path.relative(root, skillPath)} is not up to date`);
    }
    const parsed = parseFrontmatter(current, skillPath);
    validateSkillMetadata(parsed.yaml, source.yaml.name, skillPath, platform);
    return;
  }

  await rm(targetDir, { recursive: true, force: true });
  await mkdir(targetDir, { recursive: true });
  await writeFile(skillPath, markdown);
  await copyResources(source.skillDir, targetDir);
  const parsed = parseFrontmatter(markdown, skillPath);
  validateSkillMetadata(parsed.yaml, source.yaml.name, skillPath, platform);
}

async function buildSkills({ check }) {
  const skillNames = await listDirectories(sourceRoot);
  if (!skillNames.length) {
    throw new Error(`No skills found in ${path.relative(root, sourceRoot)}`);
  }

  for (const skillName of skillNames) {
    const source = await readSkillSource(skillName);
    await writeGeneratedSkill(source, "claude", check);
    await writeGeneratedSkill(source, "codex", check);
    console.log(`${check ? "Checked" : "Built"} ${skillName}`);
  }
}

async function main() {
  const options = parseArgs(process.argv.slice(2));
  if (options.importClaude && options.check) {
    throw new Error("--import-claude cannot be combined with --check");
  }
  if (options.importClaude) {
    await importClaudeSkills();
  }
  await buildSkills(options);
}

main().catch((error) => {
  console.error(error.message);
  process.exit(1);
});
